server:
  port: 8080

spring:
  main:
    web-application-type: servlet
    allow-bean-definition-overriding: true

  jpa:
    open-in-view: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration