spring:
  application:
    name: order-api
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: mysql           # config-server 에 올라간 yml 이름
    openfeign:
      circuitbreaker:
        enabled: true       # Feign에 서킷 브레이커 적용 활성화
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 3000
      okhttp:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 100

server:
  port: 10350

eureka:
  client:
    service-url:
      defaultZone: >
        http://s1.java21.net:10344/eureka,
        http://s1.java21.net:10345/eureka

payment:
  toss:
    base-url:        https//api.tosspayments.com/v1
    ## https://sandbox.tosspayments.com/v1
    client-api-key: test_ck_DLJOpm5QrlwNvJboZZaNVPNdxbWn
    secret-api-key: test_sk_Gv6LjeKD8a9512k9vamx8wYxAdXy
    success-url: http://s1.java21.net:10350/api/v1/payments/toss/success
    fail-url:    http://s1.java21.net:10350/api/v1/payments/toss/fail

management:
  endpoints:
    web:
      exposure: [health, info, mappings]
  endpoint:
    health:
      show-details: always