spring:
  application:
    name: order-api
  profiles:
    active: dev            # 실행 프로필

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  config:
    import: "optional:configserver:"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: mysql           # config-server 에 올라간 yml 이름

server:
  port: 10350

eureka:
  client:
    service-url:
      defaultZone: >
        http://s1.java21.net:10344/eureka,
        http://s1.java21.net:10345/eureka

payment:
  toss:
    sandbox: true
    test-client-api-key: test_ck_DLJOpm5QrlwNvJboZZaNVPNdxbWn
    test-secret-api-key: test_sk_Gv6LjeKD8a9512k9vamx8wYxAdXy
    success-url: http://localhost:10350/api/v1/payments/toss/success
    fail-url:     http://localhost:10350/api/v1/payments/toss/fail

management:
  endpoints:
    web:
      exposure: [health, info, mappings]
  endpoint:
    health:
      show-details: always