spring:
  application:
    name: order-api
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: "optional:configserver:"
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: mysql
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 3000
            loggerLevel: FULL
      okhttp:
        enabled: false
      httpclient:
        enabled: true

logging:
  level:
    feign:
      Logger: DEBUG
    com.nhnacademy.bookstoreorderapi.payment.client.TossPaymentClient: DEBUG
    com.nhnacademy.bookstoreorderapi.payment.service.impl.PaymentServiceImpl: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 100

server:
  port: 10351

eureka:
  client:
    service-url:
      defaultZone: >
        http://s1.java21.net:10344/eureka,
        http://s1.java21.net:10345/eureka

payment:
  toss:
    base-url:  https://sandbox.tosspayments.com/v1
    client-api-key: test_ck_DLJOpm5QrlwNvJboZZaNVPNdxbWn
    secret-api-key: test_sk_Gv6LjeKD8a9512k9vamx8wYxAdXy
    success-url: http://s1.java21.net:10350/api/v1/payments/toss/success
    fail-url:    http://s1.java21.net:10350/api/v1/payments/toss/fail

management:
  endpoints:
    web:
      exposure: [health, info, mappings]
  endpoint:
    health:
      show-details: always