spring:
  application:
    name: order-api
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: mysql

server:
  port: 10350

eureka:
  client:
    service-url:
      defaultZone: >
        http://s1.java21.net:10344/eureka,
        http://s1.java21.net:10345/eureka

payment:
  toss:
    # 여기를 꼭 추가하세요 — FeignClient(@FeignClient url="${payment.toss.base-url}") 에 바인딩됩니다
    base-url: https://sandbox.tosspayments.com/v1

    # 기존에 test-xxx 로만 올려두셨는데, 코드(TossPaymentConfig)가 기대하는 프로퍼티명으로 통일
    client-api-key: test_ck_DLJOpm5QrlwNvJboZZaNVPNdxbWn
    secret-api-key: test_sk_Gv6LjeKD8a9512k9vamx8wYxAdXy

    success-url: http://localhost:10350/api/v1/payments/toss/success
    fail-url:    http://localhost:10350/api/v1/payments/toss/fail

management:
  endpoints:
    web:
      exposure: [health, info, mappings]
  endpoint:
    health:
      show-details: always