server.port=10351

spring.application.name=order-api

spring.profiles.active=dev

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Eureka 설정
eureka.client.service-url.defaultZone=http://localhost:10344/eureka,http://localhost:10345/eureka

# Spring Cloud 설정
spring.config.import=optional:configserver:
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server
spring.cloud.config.name=mysql

# OpenFeign 설정
spring.cloud.openfeign.circuitbreaker.enabled=true
spring.cloud.openfeign.client.config.default.connect-timeout=3000
spring.cloud.openfeign.client.config.default.read-timeout=3000
spring.cloud.openfeign.client.config.default.loggerLevel=FULL
spring.cloud.openfeign.okhttp.enabled=false

# Resilience4j 설정
resilience4j.circuitbreaker.configs.default.sliding-window-size=100

# 결제(Payment) - Toss 설정
payment.toss.base-url=https://api.tosspayments.com/v1
payment.toss.client-api-key=test_ck_DLJOpm5QrlwNvJboZZaNVPNdxbWn
payment.toss.secret-api-key=test_sk_Gv6LjeKD8a9512k9vamx8wYxAdXy
payment.toss.success-url= https://bookstore-beansolid.store/pay/success
payment.toss.fail-url=  https://bookstore-beansolid.store/pay/fail

# Management (Actuator) 설정
management.endpoints.web.exposure.include=health,info,mappings
management.endpoint.health.show-details=always

# DBCP2 적용
spring.datasource.type=org.apache.commons.dbcp2.BasicDataSource

spring.datasource.dbcp2.initial-size=5
spring.datasource.dbcp2.max-total=20
spring.datasource.dbcp2.max-idle=10
spring.datasource.dbcp2.min-idle=5
spring.datasource.dbcp2.validation-query=SELECT 1
spring.datasource.dbcp2.test-on-borrow=true

# jpa 서버 시간 설정
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver