server.port=10351
spring.application.name=order-api
spring.profiles.active=dev
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
# Eureka \uC124\uC815
eureka.client.service-url.defaultZone=http://localhost:10344/eureka,http://localhost:10345/eureka
# Spring Cloud \uC124\uC815
spring.config.import=optional:configserver:
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server
spring.cloud.config.name=order-api,mysql,payments

# OpenFeign \uC124\uC815
spring.cloud.openfeign.circuitbreaker.enabled=true
spring.cloud.openfeign.client.config.default.connect-timeout=3000
spring.cloud.openfeign.client.config.default.read-timeout=60000
spring.cloud.openfeign.client.config.default.loggerLevel=FULL
spring.cloud.openfeign.okhttp.enabled=false
# Resilience4j \uC124\uC815
resilience4j.circuitbreaker.configs.default.sliding-window-size=100
# \uACB0\uC81C(Payment) - Toss \uC124\uC815
management.endpoints.web.exposure.include=health,info,mappings
management.endpoint.health.show-details=always
# DBCP2 \uC801\uC6A9
spring.datasource.type=org.apache.commons.dbcp2.BasicDataSource
spring.datasource.dbcp2.initial-size=200
spring.datasource.dbcp2.max-total=200
spring.datasource.dbcp2.max-idle=200
spring.datasource.dbcp2.min-idle=200
spring.datasource.dbcp2.validation-query=SELECT 1
spring.datasource.dbcp2.test-on-borrow=true
# jpa \uC11C\uBC84 \uC2DC\uAC04 \uC124\uC815
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
frontend.base-url=https://bookstore-beansolid.store
# application-dev.properties(??? ???)
logging.level.com.nhnacademy.bookstoreorderapi.payment=DEBUG
logging.level.io.github.openfeign=DEBUG
logging.level.feign.Logger=DEBUG