### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

### 주문 생성하기
POST s1.java21.net:10350/orders HTTP/1.1
Accept: application/json
Content-Type: application/json
X-USER-ID: test

{
  "receiverName": "홍길동",
  "receiverPhoneNumber": "01012345678",
  "zipCode": "00000",
  "baseAddress": "광주광역시",
  "detailAddress": "별관 1층 NHN 아카데미 실습실",
  "requestedDeliveryDate": "2025-12-31",
  "orderItems": [
    {
      "bookId": 99,
      "quantity": 1,
      "price": 10000,
      "wrappingId": 1
    }
  ]
}