@host = http://localhost:10350
@ct   = application/json
@memberId = 42
@guestId  = 101

### 1) 회원 주문 전체 조회
GET {{host}}/orders?userId={{memberId}}
Accept: {{ct}}



### 2) 비회원 주문 생성
POST {{host}}/orders
Content-Type: {{ct}}
Accept: {{ct}}

{
  "orderType": "guest",
  "guestId": {{guestId}},
  "orderAddress": "서울특별시 마포구 양화로 45",
  "requestedDeliveryDate": "2025-06-20",
  "items": [
    { "bookId": 1, "quantity": 1, "giftWrapped": false }
  ]
}

> {% client.global.set("orderIdGuest", response.body.orderId); %}



### 3) 회원 주문 생성
POST {{host}}/orders
Content-Type: {{ct}}
Accept: {{ct}}

{
  "orderType": "member",
  "userId": "{{memberId}}",
  "orderAddress": "서울특별시 강남구 테헤란로 123",
  "requestedDeliveryDate": "2025-06-21",
  "items": [
    { "bookId": 2, "quantity": 3, "giftWrapped": true }
  ]
}

> {% client.global.set("orderIdMember", response.body.orderId); %}



### 4) 상태 변경 (PENDING → SHIPPING)
PATCH {{host}}/orders/{{orderIdMember}}/status
Content-Type: {{ct}}
Accept: {{ct}}

{
  "newStatus": "SHIPPING",
  "changedBy": {{memberId}},
  "memo": "배송 시작"
}



### 5) 상태 변경 (SHIPPING → COMPLETED)
PATCH {{host}}/orders/{{orderIdMember}}/status
Content-Type: {{ct}}
Accept: {{ct}}

{
  "newStatus": "COMPLETED",
  "changedBy": {{memberId}},
  "memo": "배송 완료"
}



### 6) 비회원 주문 취소
POST {{host}}/orders/{{orderIdGuest}}/cancel
Content-Type: {{ct}}
Accept: {{ct}}

{
  "reason": "단순 변심",
  "changedBy": "guest-{{guestId}}"
}



### 7) 반품 요청 (회원 주문)
POST {{host}}/orders/{{orderIdMember}}/orderReturn
Content-Type: {{ct}}
Accept: {{ct}}

{
  "reason": "상품 하자",
  "changedBy": {{memberId}}
}



### 8) 상태 변경 이력 조회
GET {{host}}/orders/{{orderIdMember}}/status-log
Accept: {{ct}}


### 결제 승인 요청 테스트
POST https://api.tosspayments.com/v1/payments/confirm HTTP/1.1
Authorization: Basic dGVzdF9za19EbnlScFFXR3JOOUUwamEwcE56Z1ZLd3YxTTlFOg==
Content-Type: application/json

{
  "paymentKey":"tviva202506171743071XuQ8",
  "amount":5000000,
  "orderId":"yvce_w7-fpurCbewR7347"
}


###
POST /api/v1/payments/toss HTTP/1.1
Host: localhost:10350
Content-Type: application/json
Accept: application/json
Content-Length: 61

{
  "payType": "CARD",
  "amount": 58500,
  "orderName": "포인트 충전"
}


### 선생님꺼
POST /api/v1/payments/toss HTTP/1.1
Host: localhost:10350
Content-Type: application/json
Accept: application/json
Authorization: Basic dGVzdF9za19EbnlScFFXR3JOOUUwamEwcE56Z1ZLd3YxTTlFOg==

{
  "payType":   "CARD",
  "payAmount": 58500,
  "orderName": "테스트 결제",
  "successUrl":"http://localhost:3000/payments/success",
  "failUrl":   "http://localhost:3000/payments/fail"
}